name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Dockerhub
    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build the cross-platform builder
      run: docker buildx create --name xplatformbuilder
    - name: Build and deploy the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag tedsecretsource:latest --push .
